from pydantic import BaseModel, Field
from typing import Annotated
from datetime import datetime

class RegisterDeviceRequest(BaseModel):
    user_id: Annotated[str, Field(description="user id")]
    token: Annotated[str, Field(description="Device tokens generated by APN, FCN etc.")]
    platform: Annotated[str, Field(description="ios, android, sms, email etc.")]
    
class GetDeviceResponse(BaseModel):
    id: int 
    user_id: int
    device_token: Annotated[str, Field(description="Device token of a device")]
    platform: str
    created_at: datetime
    last_seen_at: datetime
    is_active: bool