services:
  database:
    container_name: postgresql
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./databases:/docker-entrypoint-initdb.d:ro,Z
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=notificationsdb
    ports:
      - 5433:5432

  redis-cache:
    container_name: redis-server
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-cache-data:/data
    command: ["redis-server", "--appendonly", "yes"]

  redis-queue1:
    container_name: redis-ios-queue
    image: redis 
    ports:
      - "6380:6379"
    volumes:
      - redis-queue1-data:/data 

  redis-queue2:
    container_name: redis-android-queue
    image: redis 
    ports:
      - "6381:6379"
    volumes:
      - redis-queue2-data:/data 
      
volumes:
  db-data:
  redis-cache-data:
  redis-queue1-data:
  redis-queue2-data: